# Generated by Django 5.1.1 on 2024-11-18 07:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0002_staffposition_staff_position"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="position",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
