# Generated by Django 5.1.1 on 2024-11-26 10:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0004_staffleaveapplication"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffleaveapplication",
            name="reason_declined",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
