# Generated by Django 5.1.1 on 2024-11-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0006_staffleaveapplication_leave_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffleaveapplication",
            name="leave_type",
            field=models.CharField(
                choices=[
                    ("Sick Leave", "Sick Leave"),
                    ("Vacation Leave", "Vacation Leave"),
                    ("Annual Leave", "Annual Leave"),
                    ("Maternity Leave", "Maternity Leave"),
                    ("Paternity Leave", "Paternity Leave"),
                    ("Unpaid Leave", "Unpaid Leave"),
                    ("Casual Leave", "Casual Leave"),
                    ("Privilege Leave", "Privilege Leave"),
                    ("Study Leave", "Study Leave"),
                    ("Emergency Leave", "Emergency Leave"),
                    ("Other", "Other"),
                ],
                max_length=255,
            ),
        ),
    ]
