# Generated by Django 5.1.1 on 2024-11-26 12:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0008_staffleave"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffleaveapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Approved", "Approved"),
                    ("Declined", "Declined"),
                ],
                default="Pending",
                max_length=255,
            ),
        ),
    ]
