# Generated by Django 5.1.1 on 2024-11-26 12:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("staff", "0009_alter_staffleaveapplication_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffleave",
            name="reason_cancelled",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
