# Generated by Django 4.2 on 2025-06-03 17:05

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0017_department_department_type_alter_department_school"),
        ("staff", "0010_staffleave_reason_cancelled"),
    ]

    operations = [
        migrations.CreateModel(
            name="OvertimeRecords",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("date", models.DateField()),
                ("hours", models.DecimalField(decimal_places=2, max_digits=5)),
                ("rate_per_hour", models.DecimalField(decimal_places=2, max_digits=10)),
                ("approved", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="Payslip",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("payroll_period_start", models.DateField()),
                ("payroll_period_end", models.DateField()),
                ("basic_salary", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "total_allowances",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_overtime",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "total_deductions",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("net_pay", models.DecimalField(decimal_places=2, max_digits=12)),
                ("generated_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StaffDocuments",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("ID", "National ID"),
                            ("KRA_PIN", "KRA PIN Certificate"),
                            ("NHIF", "NHIF Card"),
                            ("NSSF", "NSSF Card"),
                            ("CV", "Curriculum Vitae"),
                            ("Offer Letter", "Offer Letter"),
                            ("Other", "Other"),
                        ],
                        max_length=100,
                    ),
                ),
                ("document_file", models.FileField(upload_to="staff_documents/")),
                ("notes", models.TextField(blank=True, null=True)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="StaffPayroll",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("basic_salary", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "house_allowance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "transport_allowance",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "other_allowances",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                ("nssf_number", models.CharField(blank=True, max_length=50, null=True)),
                ("nhif_number", models.CharField(blank=True, max_length=50, null=True)),
                ("kra_pin", models.CharField(blank=True, max_length=50, null=True)),
                ("bank_name", models.CharField(blank=True, max_length=255, null=True)),
                (
                    "bank_account_number",
                    models.CharField(blank=True, max_length=255, null=True),
                ),
                (
                    "mpesa_number",
                    models.CharField(blank=True, max_length=12, null=True),
                ),
                (
                    "payment_frequency",
                    models.CharField(
                        choices=[
                            ("Monthly", "Monthly"),
                            ("Bi-Monthly", "Bi-Monthly"),
                            ("Weekly", "Weekly"),
                            ("Quarterly", "Quarterly"),
                        ],
                        default="Monthly",
                        max_length=20,
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AlterField(
            model_name="staff",
            name="department",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="schools.department"
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="position",
            field=models.CharField(default=django.utils.timezone.now, max_length=255),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name="Department",
        ),
        migrations.AddField(
            model_name="staffpayroll",
            name="staff",
            field=models.OneToOneField(
                on_delete=django.db.models.deletion.CASCADE, to="staff.staff"
            ),
        ),
        migrations.AddField(
            model_name="staffdocuments",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="documents",
                to="staff.staff",
            ),
        ),
        migrations.AddField(
            model_name="payslip",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="payslips",
                to="staff.staff",
            ),
        ),
        migrations.AddField(
            model_name="overtimerecords",
            name="staff",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="staff.staff"
            ),
        ),
    ]
