# Generated by Django 4.2 on 2025-06-03 17:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0011_overtimerecords_payslip_staffdocuments_staffpayroll_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="position",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="staff.staffposition",
            ),
        ),
    ]
