# Generated by Django 4.2 on 2025-06-04 08:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0012_alter_staff_position"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Inactive", "Inactive"),
                    ("Terminated", "Terminated"),
                    ("On Probation", "On Probation"),
                ],
                default="Active",
                max_length=20,
            ),
        ),
    ]
