# Generated by Django 4.2 on 2025-06-04 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0013_staff_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="staff",
            name="onboarding_status",
            field=models.CharField(
                choices=[
                    ("Not Started", "Not Started"),
                    ("In Progress", "In Progress"),
                    ("Completed", "Completed"),
                ],
                default="Not Started",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="staff",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Inactive", "Inactive"),
                    ("Terminated", "Terminated"),
                    ("On Probation", "On Probation"),
                ],
                default="Inactive",
                max_length=20,
            ),
        ),
    ]
