# Generated by Django 4.2 on 2025-06-04 10:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0014_staff_onboarding_status_alter_staff_status"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffOnboardingProgress",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("user_created", models.BooleanField(default=True)),
                ("staff_details_completed", models.BooleanField(default=True)),
                ("payroll_setup_completed", models.BooleanField(default=False)),
                ("documents_uploaded", models.BooleanField(default=False)),
                ("onboarding_completed", models.BooleanField(default=False)),
                (
                    "staff",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="staff.staff"
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
