# Generated by Django 4.2 on 2025-06-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0015_staffonboardingprogress"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffdocuments",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("ID", "National ID"),
                    ("KRA_PIN", "KRA PIN Certificate"),
                    ("NHIF", "NHIF Card"),
                    ("NSSF", "NSSF Card"),
                    ("CV", "Curriculum Vitae"),
                    ("Offer Letter", "Offer Letter"),
                    ("Career Certifications", "Career Certifications"),
                    ("Other", "Other"),
                ],
                max_length=100,
            ),
        ),
    ]
