# Generated by Django 4.2 on 2025-06-09 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0016_alter_staffdocuments_document_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="payslip",
            name="nhif",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="payslip",
            name="nssf",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name="payslip",
            name="paye",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
