# Generated by Django 4.2 on 2025-06-10 09:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0017_payslip_nhif_payslip_nssf_payslip_paye"),
    ]

    operations = [
        migrations.AddField(
            model_name="payslip",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("paid", "Paid"),
                    ("reversed", "Reversed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=10,
            ),
        ),
    ]
