# Generated by Django 4.2 on 2025-06-10 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0018_payslip_payment_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staff",
            name="staff_number",
            field=models.CharField(max_length=255, unique=True),
        ),
    ]
