# Generated by Django 4.2 on 2025-06-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0019_alter_staff_staff_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="staffleaveapplication",
            name="reason_declined",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
