# Generated by Django 4.2 on 2025-06-13 09:47

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0020_alter_staffleaveapplication_reason_declined"),
    ]

    operations = [
        migrations.CreateModel(
            name="StaffLeaveEntitlement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField(default=2025)),
                ("total_days", models.PositiveIntegerField(default=21)),
                ("used_days", models.PositiveIntegerField(default=0)),
                (
                    "staff",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE, to="staff.staff"
                    ),
                ),
            ],
        ),
    ]
