# Generated by Django 4.2 on 2025-06-29 08:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0021_staffleaveentitlement"),
    ]

    operations = [
        migrations.AddField(
            model_name="staffleaveentitlement",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="staffleaveentitlement",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
