# Generated by Django 4.2 on 2025-08-09 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("staff", "0022_staffleaveentitlement_created_on_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="payslip",
            name="payment_status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("processing", "Processing"),
                    ("partially_paid", "Partially Paid"),
                    ("paid", "Paid"),
                    ("reversed", "Reversed"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=50,
            ),
        ),
    ]
