# Generated by Django 4.2 on 2025-07-08 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0002_tender_status_tenderaward"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="actual_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="The actual awarded amount for the tender",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="tender",
            name="projected_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="The projected cost for the tender",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="tenderaward",
            name="award_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="The final agreed amount for the award",
                max_digits=12,
            ),
        ),
    ]
