# Generated by Django 4.2 on 2025-07-08 10:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0003_tender_actual_amount_tender_projected_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tender",
            name="status",
            field=models.CharField(
                choices=[("open", "Open"), ("awarded", "Awarded")],
                default="open",
                max_length=20,
            ),
        ),
    ]
