# Generated by Django 4.2 on 2025-07-08 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0005_vendorpayment_purchaseorder_purchaseitem_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseitem",
            name="name",
            field=models.CharField(
                default=1,
                help_text="Short name of the item e.g., 'Office Desk'",
                max_length=100,
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="purchaseitem",
            name="unit",
            field=models.CharField(
                default=1,
                help_text="Unit of measure, e.g., pcs, reams, litres",
                max_length=50,
            ),
            preserve_default=False,
        ),
    ]
