# Generated by Django 4.2 on 2025-07-08 12:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0001_initial"),
        ("procurement", "0006_purchaseitem_name_purchaseitem_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseitem",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.category",
            ),
        ),
    ]
