# Generated by Django 4.2 on 2025-07-29 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0007_purchaseitem_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="end_date",
            field=models.DateField(
                blank=True,
                help_text="Expected end date of the tender execution",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tender",
            name="start_date",
            field=models.DateField(
                blank=True,
                help_text="Expected start date of the tender execution",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="business_type",
            field=models.CharField(
                blank=True,
                help_text="E.g., Sole Proprietor, Partnership, Ltd, NGO",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="company_registration_number",
            field=models.CharField(
                blank=True,
                help_text="Company Registration Number or Business Number",
                max_length=100,
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="contact_person",
            field=models.CharField(
                blank=True,
                help_text="Name of the main contact at the company",
                max_length=255,
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="contact_person_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="vendor",
            name="contact_person_phone",
            field=models.CharField(blank=True, max_length=20),
        ),
        migrations.AddField(
            model_name="vendor",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("inactive", "Inactive"),
                    ("blacklisted", "Blacklisted"),
                ],
                default="active",
                max_length=20,
            ),
        ),
        migrations.AddField(
            model_name="vendor",
            name="tax_pin",
            field=models.CharField(
                blank=True, help_text="KRA PIN or equivalent", max_length=100
            ),
        ),
    ]
