# Generated by Django 4.2 on 2025-07-29 16:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0008_tender_end_date_tender_start_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="vendor",
            name="business_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("individual", "Individual"),
                    ("sole_proprietor", "Sole Proprietor"),
                    ("partnership", "Partnership"),
                    ("limited", "Limited Company"),
                    ("ngo", "NGO"),
                    ("government", "Government"),
                    ("other", "Other"),
                ],
                help_text="Type of business",
                max_length=50,
                null=True,
            ),
        ),
    ]
