# Generated by Django 4.2 on 2025-07-29 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0009_alter_vendor_business_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenderaward",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("terminated", "Terminated"),
                    ("cancelled", "Cancelled"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
