# Generated by Django 4.2 on 2025-07-29 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0010_tenderaward_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="vendor_no",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
