# Generated by Django 4.2 on 2025-07-30 06:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0011_vendor_vendor_no"),
    ]

    operations = [
        migrations.AddField(
            model_name="tender",
            name="tender_document",
            field=models.FileField(
                blank=True,
                help_text="Upload tender details and terms document",
                null=True,
                upload_to="tender_docs/",
            ),
        ),
        migrations.AddField(
            model_name="tenderapplication",
            name="business_type",
            field=models.CharField(
                blank=True,
                choices=[
                    ("individual", "Individual"),
                    ("sole_proprietor", "Sole Proprietor"),
                    ("partnership", "Partnership"),
                    ("limited", "Limited Company"),
                    ("ngo", "NGO"),
                    ("government", "Government"),
                    ("other", "Other"),
                ],
                help_text="Type of business applying",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="tenderapplication",
            name="company_registration_number",
            field=models.CharField(
                blank=True, help_text="Business registration number", max_length=100
            ),
        ),
        migrations.AddField(
            model_name="tenderapplication",
            name="contact_person",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="tenderapplication",
            name="contact_person_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="tenderapplication",
            name="contact_person_phone",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="tenderapplication",
            name="tax_pin",
            field=models.CharField(
                blank=True, help_text="KRA PIN or equivalent", max_length=100
            ),
        ),
        migrations.CreateModel(
            name="VendorDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("document_name", models.CharField(max_length=255)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            (
                                "certificate_of_incorporation",
                                "Certificate of Incorporation",
                            ),
                            ("proposal_document", "Proposal Document"),
                            ("business_registration", "Business Registration"),
                            ("tax_compliance", "Tax Compliance Certificate"),
                            ("audited_financials", "Audited Financial Statements"),
                            ("bank_statements", "Bank Statements"),
                            ("tax_clearance", "Tax Clearance Certificate"),
                            ("professional_license", "Professional License"),
                            ("insurance_certificate", "Insurance Certificate"),
                            ("company_profile", "Company Profile"),
                            ("technical_proposal", "Technical Proposal"),
                            ("financial_proposal", "Financial Proposal"),
                            ("performance_bond", "Performance Bond"),
                            ("bid_security", "Bid Security"),
                            ("experience_certificates", "Experience Certificates"),
                            ("quality_certificates", "Quality Certificates"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("document_file", models.FileField(upload_to="vendor_documents/")),
                ("description", models.TextField(blank=True)),
                (
                    "source_application",
                    models.ForeignKey(
                        blank=True,
                        help_text="Application this document was copied from",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="procurement.tenderapplication",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="procurement.vendor",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ApplicationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("document_name", models.CharField(max_length=255)),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            (
                                "certificate_of_incorporation",
                                "Certificate of Incorporation",
                            ),
                            ("proposal_document", "Proposal Document"),
                            ("business_registration", "Business Registration"),
                            ("tax_compliance", "Tax Compliance Certificate"),
                            ("audited_financials", "Audited Financial Statements"),
                            ("bank_statements", "Bank Statements"),
                            ("tax_clearance", "Tax Clearance Certificate"),
                            ("professional_license", "Professional License"),
                            ("insurance_certificate", "Insurance Certificate"),
                            ("company_profile", "Company Profile"),
                            ("technical_proposal", "Technical Proposal"),
                            ("financial_proposal", "Financial Proposal"),
                            ("performance_bond", "Performance Bond"),
                            ("bid_security", "Bid Security"),
                            ("experience_certificates", "Experience Certificates"),
                            ("quality_certificates", "Quality Certificates"),
                            ("other", "Other"),
                        ],
                        max_length=50,
                    ),
                ),
                ("file", models.FileField(upload_to="application_documents/")),
                ("description", models.TextField(blank=True)),
                (
                    "application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="documents",
                        to="procurement.tenderapplication",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
