# Generated by Django 4.2 on 2025-07-30 07:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0012_tender_tender_document_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenderapplication",
            name="vendor_no",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
