# Generated by Django 4.2 on 2025-07-30 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0013_tenderapplication_vendor_no"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenderapplication",
            name="company_name",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="tenderapplication",
            name="email",
            field=models.EmailField(blank=True, max_length=254),
        ),
        migrations.AlterField(
            model_name="tenderapplication",
            name="phone",
            field=models.CharField(blank=True, max_length=20),
        ),
    ]
