# Generated by Django 4.2 on 2025-07-30 13:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0014_alter_tenderapplication_company_name_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenderapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("approved", "Approved"),
                    ("rejected", "Rejected"),
                    ("incomplete", "Incomplete"),
                ],
                default="incomplete",
                max_length=20,
            ),
        ),
    ]
