# Generated by Django 4.2 on 2025-07-31 18:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0015_alter_tenderapplication_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tender",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("awarded", "Awarded"),
                    ("cancelled", "Cancelled"),
                ],
                default="open",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="tenderaward",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Active"),
                    ("completed", "Completed"),
                    ("terminated", "Terminated"),
                    ("cancelled", "Cancelled"),
                    ("revoked", "Revoked"),
                ],
                default="active",
                max_length=20,
            ),
        ),
    ]
