# Generated by Django 4.2 on 2025-08-01 07:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0016_alter_tender_status_alter_tenderaward_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="tenderaward",
            name="tender",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="awards",
                to="procurement.tender",
            ),
        ),
    ]
