# Generated by Django 4.2 on 2025-08-01 08:12

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0018_tenderaward_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="tenderaward",
            name="amount_paid",
            field=models.DecimalField(
                decimal_places=2,
                default=0.0,
                help_text="Total amount paid to vendor for this award",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="vendorpayment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("Cash", "Cash"),
                    ("Bank", "Bank Transfer"),
                    ("Mpesa", "Mpesa"),
                    ("Cheque", "Cheque"),
                ],
                default=django.utils.timezone.now,
                max_length=50,
            ),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name="VendorPaymentStatement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "statement_type",
                    models.CharField(
                        choices=[("Award", "Award"), ("Payment", "Payment")],
                        max_length=20,
                    ),
                ),
                (
                    "debit",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "credit",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "payment_method",
                    models.CharField(
                        blank=True,
                        choices=[
                            ("Cash", "Cash"),
                            ("Bank", "Bank Transfer"),
                            ("Mpesa", "Mpesa"),
                            ("Cheque", "Cheque"),
                        ],
                        max_length=50,
                        null=True,
                    ),
                ),
                (
                    "tender_award",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="procurement.tenderaward",
                    ),
                ),
                (
                    "vendor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="procurement.vendor",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
