# Generated by Django 4.2 on 2025-08-01 11:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        (
            "procurement",
            "0019_tenderaward_amount_paid_vendorpayment_payment_method_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="vendorpayment",
            name="description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="vendorpayment",
            name="tender_award",
            field=models.ForeignKey(
                default=1,
                on_delete=django.db.models.deletion.CASCADE,
                to="procurement.tenderaward",
            ),
            preserve_default=False,
        ),
    ]
