# Generated by Django 4.2 on 2025-08-01 11:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0020_vendorpayment_description_vendorpayment_tender_award"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="vendorpayment",
            name="vendor",
        ),
    ]
