# Generated by Django 4.2 on 2025-08-02 17:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_unitofmeasure_alter_inventoryitem_unit"),
        ("procurement", "0021_remove_vendorpayment_vendor"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseitem",
            name="unit",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="inventory.unitofmeasure",
            ),
        ),
        migrations.CreateModel(
            name="PurchaseItemReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity_received", models.PositiveIntegerField()),
                ("received_on", models.DateTimeField(auto_now_add=True)),
                (
                    "goods_received",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="procurement.goodsreceived",
                    ),
                ),
                (
                    "purchase_item",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="procurement.purchaseitem",
                    ),
                ),
            ],
        ),
    ]
