# Generated by Django 4.2 on 2025-08-03 07:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0022_alter_purchaseitem_unit_purchaseitemreceipt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchaseitem",
            name="description",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
