# Generated by Django 4.2 on 2025-08-03 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("procurement", "0023_alter_purchaseitem_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchaseorder",
            name="order_no",
            field=models.CharField(blank=True, max_length=20, null=True, unique=True),
        ),
    ]
