# Generated by Django 4.2 on 2025-06-02 07:32

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_finance", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentfeeinvoice",
            name="amount",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="studentfeeinvoice",
            name="amount_paid",
            field=models.DecimalField(
                decimal_places=2, default=Decimal("0"), max_digits=10
            ),
        ),
        migrations.AddField(
            model_name="studentfeeinvoice",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Paid", "Paid"),
                    ("Partially Paid", "Partially Paid"),
                ],
                default="Pending",
                max_length=255,
            ),
        ),
    ]
