# Generated by Django 4.2 on 2025-06-02 09:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_finance", "0002_studentfeeinvoice_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentfeeinvoice",
            name="description",
            field=models.CharField(
                choices=[
                    ("Standard Invoice", "Standard Invoice"),
                    ("Trip Invoice", "Trip Invoice"),
                    ("Graduation Invoice", "Graduation Invoice"),
                ],
                default="Standard Invoice",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="studentfeeinvoice",
            name="reference",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
