# Generated by Django 4.2 on 2025-06-02 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_finance", "0004_studentfeestatement"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentfeestatement",
            name="transaction_type",
            field=models.CharField(
                choices=[
                    ("Standard Invoice", "Standard Invoice"),
                    ("Student Payment", "Student Payment"),
                    ("Trip Invoice", "Trip Invoice"),
                    ("Graduation Invoice", "Graduation Invoice"),
                ],
                default="Standard Invoice",
                max_length=255,
            ),
        ),
    ]
