# Generated by Django 4.2 on 2025-06-03 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0016_alter_coursesession_cohort"),
        ("student_finance", "0005_studentfeestatement_transaction_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentfeestatement",
            name="semester",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="schools.semester",
            ),
        ),
    ]
