# Generated by Django 4.2 on 2025-06-23 13:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_finance", "0006_studentfeestatement_semester"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentfeestatement",
            name="payment_method",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Mpesa", "Mpesa"),
                    ("Bank Transfer", "Bank Transfer"),
                    ("Cash", "Cash"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
