# Generated by Django 5.2.5 on 2025-08-19 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_finance", "0009_studentfeeinvoice_created_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentfeepayment",
            name="reference",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
