# Generated by Django 5.2.5 on 2025-08-19 16:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("student_finance", "0010_studentfeepayment_reference"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentfeestatement",
            name="reference",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
