# Generated by Django 5.1.1 on 2024-11-20 08:22

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0001_initial"),
        ("library", "0005_borrowtransaction_issued_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="libraryfinepayment",
            name="fine",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="library.fine",
            ),
        ),
        migrations.AddField(
            model_name="libraryfinepayment",
            name="paid",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="libraryfinepayment",
            name="payment_date",
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name="libraryfinepayment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("Cash", "Cash"),
                    ("Bank Transfer", "Bank Transfer"),
                    ("Mobile Money", "Mobile Money"),
                    ("Cheque", "Cheque"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
