# Generated by Django 5.1.1 on 2024-11-20 08:30

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0002_libraryfinepayment_fine_libraryfinepayment_paid_and_more"),
        ("library", "0005_borrowtransaction_issued_by"),
    ]

    operations = [
        migrations.AlterField(
            model_name="libraryfinepayment",
            name="fine",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="finepayment",
                to="library.fine",
            ),
        ),
    ]
