# Generated by Django 5.1.1 on 2024-11-25 16:53

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0004_alter_payment_payer_alter_payment_receiver"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="description",
            field=models.CharField(max_length=500, null=True),
        ),
    ]
