# Generated by Django 5.1.1 on 2024-11-25 16:59

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("finance", "0005_payment_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="payment",
            name="payment_reference",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
