# Generated by Django 5.1.4 on 2024-12-11 13:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("finance", "0007_feestructure_feestructureitem"),
    ]

    operations = [
        migrations.AlterField(
            model_name="feestructureitem",
            name="fee_structure",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="feeitems",
                to="finance.feestructure",
            ),
        ),
    ]
