# Generated by Django 5.1.1 on 2024-11-07 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0006_alter_mealcard_month"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="guardian_name",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="guardian_phone_number",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
