# Generated by Django 5.1.1 on 2024-11-08 14:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0005_alter_semester_name"),
        ("students", "0007_student_guardian_name_student_guardian_phone_number"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="programme",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="schools.programme",
            ),
        ),
    ]
