# Generated by Django 5.1.1 on 2024-11-17 10:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0009_studenteducationhistory"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studenteducationhistory",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="educationhistory",
                to="students.student",
            ),
        ),
    ]
