# Generated by Django 5.1.1 on 2024-11-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0011_studentprogramme"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="guardian_email",
            field=models.EmailField(max_length=254, null=True),
        ),
        migrations.AddField(
            model_name="student",
            name="guardian_relationship",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
