# Generated by Django 5.1.1 on 2024-11-18 18:45

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0008_programmecohort_coursesession"),
        ("students", "0013_studentattendance"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentattendance",
            name="session",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="schools.coursesession",
            ),
        ),
        migrations.AlterField(
            model_name="studentattendance",
            name="status",
            field=models.CharField(
                choices=[("Present", "Present"), ("Absent", "Absent")],
                max_length=255,
                null=True,
            ),
        ),
    ]
