# Generated by Django 5.1.1 on 2024-11-18 18:47

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0014_studentattendance_session_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentattendance",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="studentattendances",
                to="students.student",
            ),
        ),
    ]
