# Generated by Django 5.1.1 on 2024-11-19 11:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0015_alter_coursesession_status"),
        ("students", "0016_student_cohort"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentattendance",
            name="session",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="sessionattendances",
                to="schools.coursesession",
            ),
        ),
        migrations.AlterField(
            model_name="studentattendance",
            name="status",
            field=models.CharField(
                choices=[("Present", "Present"), ("Absent", "Absent")],
                default="Present",
                max_length=255,
            ),
        ),
    ]
