# Generated by Django 5.1.1 on 2024-11-19 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0015_alter_coursesession_status"),
        ("students", "0017_alter_studentattendance_session_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="student",
            name="cohort",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cohortstudents",
                to="schools.programmecohort",
            ),
        ),
    ]
