# Generated by Django 5.1.1 on 2024-11-21 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0018_alter_student_cohort"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studenteducationhistory",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="studenteducationhistory",
            name="start_date",
        ),
        migrations.AddField(
            model_name="studenteducationhistory",
            name="grade_or_gpa",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="studenteducationhistory",
            name="major",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="studenteducationhistory",
            name="year",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
