# Generated by Django 5.1.1 on 2024-11-21 10:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("students", "0019_remove_studenteducationhistory_end_date_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="studentdocument",
            old_name="file",
            new_name="document_file",
        ),
        migrations.RenameField(
            model_name="studentdocument",
            old_name="name",
            new_name="document_name",
        ),
        migrations.AddField(
            model_name="studentdocument",
            name="document_type",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
