# Generated by Django 5.1.1 on 2024-11-21 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hostels", "0004_alter_hostel_gender"),
        ("students", "0020_rename_file_studentdocument_document_file_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="hostel_room",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="hostels.hostelroom",
            ),
        ),
    ]
