# Generated by Django 5.1.1 on 2024-11-25 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0004_checkin"),
        ("students", "0022_studentcheckin"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="campus",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.campus",
            ),
        ),
    ]
