# Generated by Django 4.2 on 2025-05-02 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0024_alter_mealcard_month'),
        ('students', '0024_alter_mealcard_month_alter_mealcard_year'),
    ]

    operations = [
    ]
