# Generated by Django 4.2 on 2025-06-02 06:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0026_alter_mealcard_month"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mealcard",
            name="month",
            field=models.CharField(
                choices=[
                    ("January", "January"),
                    ("February", "February"),
                    ("March", "March"),
                    ("April", "April"),
                    ("May", "May"),
                    ("June", "June"),
                    ("July", "July"),
                    ("August", "August"),
                    ("September", "September"),
                    ("October", "October"),
                    ("November", "November"),
                    ("December", "December"),
                ],
                default="June",
                max_length=255,
            ),
        ),
    ]
