# Generated by Django 4.2 on 2025-06-03 13:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0028_semesterreporting"),
    ]

    operations = [
        migrations.AlterField(
            model_name="semesterreporting",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="students.student"
            ),
        ),
    ]
