# Generated by Django 4.2 on 2025-06-19 08:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0018_programmecohort_intake"),
        ("students", "0029_alter_semesterreporting_student"),
    ]

    operations = [
        migrations.AddField(
            model_name="semesterreporting",
            name="academic_year",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="semesterreporting",
            name="cohort",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="schools.programmecohort",
            ),
        ),
        migrations.AddField(
            model_name="semesterreporting",
            name="promoted",
            field=models.BooleanField(default=False),
        ),
    ]
