# Generated by Django 4.2 on 2025-06-19 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0030_semesterreporting_academic_year_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="semesterreporting",
            name="reported",
            field=models.BooleanField(default=False),
        ),
    ]
