# Generated by Django 4.2 on 2025-06-19 10:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0031_semesterreporting_reported"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="semesterreporting",
            name="promoted",
        ),
    ]
