# Generated by Django 5.2.5 on 2025-08-23 17:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0034_studentcourseenrollment"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentcourseenrollment",
            name="approved",
            field=models.BooleanField(default=False),
        ),
    ]
