# Generated by Django 5.2.5 on 2025-08-23 17:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0035_studentcourseenrollment_approved"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="studentcourseenrollment",
            name="academic_year",
        ),
    ]
