# Generated by Django 5.2.5 on 2025-10-05 06:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0002_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="academicyear",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="academicyear",
            name="start_date",
        ),
    ]
