# Generated by Django 5.1.1 on 2024-11-17 08:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_campus"),
    ]

    operations = [
        migrations.AddField(
            model_name="campus",
            name="population",
            field=models.IntegerField(null=True),
        ),
    ]
