# Generated by Django 5.2.5 on 2025-10-05 06:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_academicyear_end_date_academicyear_start_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="academicyear",
            name="end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="academicyear",
            name="start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
