# Generated by Django 5.1.4 on 2024-12-11 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0004_checkin"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudyYear",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
