# Generated by Django 4.2 on 2025-06-30 14:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_studyyear"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campus",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="campus",
            name="email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="campus",
            name="phone_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="campus",
            name="population",
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
