# Generated by Django 5.2.5 on 2025-08-10 09:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_module_rolepermission'),
    ]

    operations = [
        migrations.AlterField(
            model_name='rolepermission',
            name='can_view',
            field=models.BooleanField(default=True),
        ),
    ]
