# Generated by Django 5.1.7 on 2025-09-08 07:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_academicyear'),
        ('core', '0009_module_created_on_module_updated_on_and_more'),
    ]

    operations = [
    ]
