# Generated by Django 5.2.5 on 2025-08-23 16:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0007_academicyear"),
        ("core", "0009_module_created_on_module_updated_on_and_more"),
    ]

    operations = []
