# Generated by Django 5.2.5 on 2025-09-24 05:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_merge_20250908_1036'),
    ]

    operations = [
        migrations.AddField(
            model_name='rolepermission',
            name='can_view_all',
            field=models.BooleanField(default=False),
        ),
    ]
