# Generated by Django 5.2.5 on 2025-08-23 17:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0010_merge_20250823_1946"),
    ]

    operations = [
        migrations.AddField(
            model_name="academicyear",
            name="is_current",
            field=models.BooleanField(default=False),
        ),
    ]
