# Generated by Django 5.2.5 on 2025-09-24 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_rolepermission_can_view_all'),
    ]

    operations = [
        migrations.AddField(
            model_name='userrole',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
