# Generated by Django 4.2 on 2025-07-24 10:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0002_account_created_on_account_updated_on_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_contra",
            field=models.BooleanField(default=False),
        ),
    ]
