# Generated by Django 4.2 on 2025-07-26 06:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0003_account_is_contra"),
    ]

    operations = [
        migrations.AddField(
            model_name="account",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="accounttype",
            name="is_archived",
            field=models.BooleanField(default=False),
        ),
    ]
