# Generated by Django 4.2 on 2025-07-26 07:26

from django.db import migrations, models
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0004_account_is_archived_accounttype_is_archived"),
    ]

    operations = [
        migrations.AlterModelManagers(
            name="account",
            managers=[
                ("active", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AlterModelManagers(
            name="accounttype",
            managers=[
                ("active", django.db.models.manager.Manager()),
            ],
        ),
        migrations.AddField(
            model_name="account",
            name="normal_balance",
            field=models.CharField(
                blank=True,
                choices=[("debit", "Debit"), ("credit", "Credit")],
                editable=False,
                max_length=6,
                null=True,
            ),
        ),
    ]
