# Generated by Django 4.2 on 2025-07-26 11:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "accounting",
            "0005_alter_account_managers_alter_accounttype_managers_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="accounttype",
            name="cash_flow_section",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Operating", "Operating"),
                    ("Investing", "Investing"),
                    ("Financing", "Financing"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
