# Generated by Django 4.2 on 2025-07-26 15:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0006_accounttype_cash_flow_section"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="accounttype",
            name="cash_flow_section",
        ),
        migrations.AddField(
            model_name="account",
            name="cash_flow_section",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Operating", "Operating"),
                    ("Investing", "Investing"),
                    ("Financing", "Financing"),
                ],
                max_length=20,
                null=True,
            ),
        ),
    ]
