# Generated by Django 5.1.1 on 2024-11-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("payments", "0004_mealcardpayment_mealcard"),
    ]

    operations = [
        migrations.AlterField(
            model_name="mealcardpayment",
            name="month",
            field=models.CharField(
                choices=[
                    ("January", "January"),
                    ("February", "February"),
                    ("March", "March"),
                    ("April", "April"),
                    ("May", "May"),
                    ("June", "June"),
                    ("July", "July"),
                    ("August", "August"),
                    ("September", "September"),
                    ("October", "October"),
                    ("November", "November"),
                    ("December", "December"),
                ],
                default="November",
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="rentpayment",
            name="month",
            field=models.CharField(
                choices=[
                    ("January", "January"),
                    ("February", "February"),
                    ("March", "March"),
                    ("April", "April"),
                    ("May", "May"),
                    ("June", "June"),
                    ("July", "July"),
                    ("August", "August"),
                    ("September", "September"),
                    ("October", "October"),
                    ("November", "November"),
                    ("December", "December"),
                ],
                default="November",
                max_length=255,
            ),
        ),
    ]
