# Generated by Django 4.2 on 2025-05-02 12:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('payments', '0006_alter_mealcardpayment_month_alter_rentpayment_month'),
        ('payments', '0006_alter_mealcardpayment_month_and_more'),
    ]

    operations = [
    ]
