# Generated by Django 5.1.1 on 2024-11-18 06:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_date_of_birth"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="state",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
