# Generated by Django 5.1.1 on 2024-11-18 06:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_user_state"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="postal_code",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
