# Generated by Django 5.1.1 on 2024-11-21 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_user_postal_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="id_number",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="user",
            name="passport_number",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
