# Generated by Django 4.2 on 2025-08-03 07:26

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0002_unitofmeasure_alter_inventoryitem_unit"),
    ]

    operations = [
        migrations.AddField(
            model_name="unitofmeasure",
            name="created_on",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="unitofmeasure",
            name="updated_on",
            field=models.DateTimeField(auto_now=True),
        ),
    ]
