# Generated by Django 4.2 on 2025-08-03 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0003_unitofmeasure_created_on_unitofmeasure_updated_on"),
    ]

    operations = [
        migrations.AddField(
            model_name="category",
            name="category_type",
            field=models.CharField(
                choices=[
                    ("fixed_asset", "Fixed Asset"),
                    ("inventory", "Inventory"),
                    ("consumable", "Consumable"),
                    ("service", "Service"),
                    ("other", "Other"),
                ],
                default="inventory",
                max_length=20,
            ),
        ),
    ]
