# Generated by Django 4.2 on 2025-08-06 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0005_inventoryitem_total_valuation_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryitem",
            name="total_valuation",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                help_text="Total value (for fixed assets or special cases)",
                max_digits=14,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="inventoryitem",
            name="unit_valuation",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                default=0.0,
                help_text="Cost per unit (for inventory items)",
                max_digits=12,
                null=True,
            ),
        ),
    ]
