# Generated by Django 5.1.1 on 2024-11-09 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketing", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lead",
            name="created_at",
        ),
        migrations.RemoveField(
            model_name="lead",
            name="updated_at",
        ),
        migrations.AddField(
            model_name="lead",
            name="gender",
            field=models.CharField(
                blank=True,
                choices=[("Male", "Male"), ("Female", "Female")],
                max_length=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="campaign",
            name="campaign_type",
            field=models.CharField(
                choices=[
                    ("Email", "Email Campaign"),
                    ("Social Media", "Social Media Campaign"),
                    ("Webinar", "Webinar"),
                    ("Event", "Event"),
                ],
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="interaction",
            name="interaction_type",
            field=models.CharField(
                choices=[
                    ("Email", "Email"),
                    ("Phone", "Phone"),
                    ("SMS", "SMS"),
                    ("Meeting", "Meeting"),
                    ("Event", "Event"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Contacted", "Contacted"),
                    ("Interested", "Interested"),
                    ("Application in Progress", "Application in Progress"),
                    ("Converted", "Converted"),
                    ("Lost", "Lost"),
                ],
                default="new",
                max_length=50,
            ),
        ),
        migrations.AlterField(
            model_name="leadstage",
            name="stage",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Contacted", "Contacted"),
                    ("Interested", "Interested"),
                    ("Application in Progress", "Application in Progress"),
                    ("Converted", "Converted"),
                    ("Lost", "Lost"),
                ],
                max_length=50,
            ),
        ),
    ]
