# Generated by Django 5.1.1 on 2024-11-09 11:19

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketing", "0002_remove_lead_created_at_remove_lead_updated_at_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="status",
            field=models.CharField(
                choices=[
                    ("New", "New"),
                    ("Contacted", "Contacted"),
                    ("Interested", "Interested"),
                    ("Application in Progress", "Application in Progress"),
                    ("Converted", "Converted"),
                    ("Lost", "Lost"),
                ],
                default="New",
                max_length=50,
            ),
        ),
    ]
