# Generated by Django 5.1.1 on 2024-11-09 11:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketing", "0003_alter_lead_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="lead",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="lead",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
