# Generated by Django 5.1.1 on 2024-11-09 11:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketing", "0004_lead_city_lead_country"),
        ("schools", "0005_alter_semester_name"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="lead",
            name="program_interest",
        ),
        migrations.AddField(
            model_name="lead",
            name="programme",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="schools.programme",
            ),
        ),
    ]
