# Generated by Django 5.1.1 on 2024-11-09 12:44

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketing", "0005_remove_lead_program_interest_lead_programme"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="image",
            field=models.ImageField(
                blank=True, null=True, upload_to="campaigns_images/"
            ),
        ),
    ]
