# Generated by Django 5.1.1 on 2024-11-09 12:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketing", "0006_campaign_image"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="status",
            field=models.CharField(
                choices=[
                    ("Draft", "Draft"),
                    ("In Progress", "In Progress"),
                    ("Completed", "Completed"),
                ],
                default="Draft",
                max_length=50,
            ),
        ),
    ]
