# Generated by Django 5.1.1 on 2024-11-12 09:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketing", "0008_campaign_views"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="campaign_link",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="campaign",
            name="slug",
            field=models.SlugField(blank=True, null=True, unique=True),
        ),
    ]
