# Generated by Django 5.1.1 on 2024-11-12 10:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketing", "0009_campaign_campaign_link_campaign_slug"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="campaign",
            name="leads",
        ),
        migrations.AddField(
            model_name="lead",
            name="campaign",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leads",
                to="marketing.campaign",
            ),
        ),
    ]
