# Generated by Django 5.1.1 on 2024-11-12 10:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketing", "0010_remove_campaign_leads_lead_campaign"),
    ]

    operations = [
        migrations.AlterField(
            model_name="lead",
            name="email",
            field=models.EmailField(max_length=254),
        ),
    ]
