# Generated by Django 5.1.1 on 2024-11-12 11:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketing", "0011_alter_lead_email"),
    ]

    operations = [
        migrations.AddField(
            model_name="campaign",
            name="budget",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
