# Generated by Django 5.1.1 on 2024-11-12 15:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketing", "0012_campaign_budget"),
    ]

    operations = [
        migrations.AlterField(
            model_name="campaign",
            name="campaign_type",
            field=models.CharField(
                choices=[
                    ("Email", "Email Campaign"),
                    ("Social Media", "Social Media Campaign"),
                    ("Webinar", "Webinar"),
                    ("Event", "Event"),
                    ("Phone Call", "Phone Call"),
                ],
                max_length=50,
            ),
        ),
    ]
