# Generated by Django 5.1.1 on 2024-11-20 15:38

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("marketing", "0015_leadstage_added_by"),
    ]

    operations = [
        migrations.RenameField(
            model_name="lead",
            old_name="name",
            new_name="first_name",
        ),
        migrations.AddField(
            model_name="lead",
            name="last_name",
            field=models.CharField(default=1, max_length=255),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="lead",
            name="source",
            field=models.CharField(max_length=100),
        ),
    ]
