# Generated by Django 5.1.1 on 2024-11-23 17:19

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visitors", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="checkin_time",
            field=models.DateTimeField(
                auto_now_add=True, default=django.utils.timezone.now
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="visitor",
            name="checkout_time",
            field=models.DateTimeField(null=True),
        ),
    ]
