# Generated by Django 5.1.1 on 2024-11-23 17:39

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("visitors", "0002_visitor_checkin_time_visitor_checkout_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="gender",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
