# Generated by Django 5.1.1 on 2024-11-07 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("schools", "0004_semester"),
        ("students", "0006_alter_mealcard_month"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="ExamData",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                (
                    "cat_one",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "cat_two",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "main_exam",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_marks",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="schools.course"
                    ),
                ),
                (
                    "recorded_by",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
                (
                    "semester",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        to="schools.semester",
                    ),
                ),
                (
                    "student",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="students.student",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
