# Generated by Django 5.1.1 on 2024-11-07 13:53

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="examdata",
            old_name="main_exam",
            new_name="exam_marks",
        ),
    ]
