# Generated by Django 5.1.1 on 2024-11-08 11:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0002_rename_main_exam_examdata_exam_marks"),
        ("students", "0007_student_guardian_name_student_guardian_phone_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examdata",
            name="student",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="studentmarks",
                to="students.student",
            ),
        ),
    ]
