# Generated by Django 5.1.1 on 2024-11-08 16:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0003_alter_examdata_student"),
        ("schools", "0005_alter_semester_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="examdata",
            name="semester",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="semestermarks",
                to="schools.semester",
            ),
        ),
    ]
