# Generated by Django 5.1.1 on 2024-11-22 18:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("exams", "0004_alter_examdata_semester"),
        ("schools", "0016_alter_coursesession_cohort"),
    ]

    operations = [
        migrations.AddField(
            model_name="examdata",
            name="cohort",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="cohortmarks",
                to="schools.programmecohort",
            ),
        ),
    ]
