# Generated by Django 4.2 on 2025-05-20 08:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0005_examdata_cohort"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="examdata",
            constraint=models.UniqueConstraint(
                fields=("student", "semester", "cohort", "course"),
                name="unique_exam_per_student_course_semester_cohort",
            ),
        ),
    ]
