# Generated by Django 4.2 on 2025-05-20 09:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("exams", "0006_examdata_unique_exam_per_student_course_semester_cohort"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="examdata",
            name="unique_exam_per_student_course_semester_cohort",
        ),
    ]
