# Generated by Django 5.1.1 on 2024-11-20 09:19

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("schools", "0016_alter_coursesession_cohort"),
    ]

    operations = [
        migrations.CreateModel(
            name="StudentApplication",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("first_name", models.CharField(max_length=50)),
                ("last_name", models.CharField(max_length=50)),
                ("email", models.EmailField(max_length=254)),
                ("phone_number", models.CharField(max_length=20)),
                ("id_number", models.CharField(max_length=255, null=True)),
                ("passport_number", models.CharField(max_length=255, null=True)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")], max_length=255
                    ),
                ),
                ("guardian_name", models.CharField(max_length=255, null=True)),
                ("guardian_email", models.EmailField(max_length=254, null=True)),
                ("guardian_relationship", models.CharField(max_length=255, null=True)),
                ("guardian_phone_number", models.CharField(max_length=255, null=True)),
                ("address", models.CharField(max_length=255, null=True)),
                ("postal_code", models.CharField(max_length=255, null=True)),
                ("city", models.CharField(max_length=255, null=True)),
                ("country", models.CharField(max_length=255, null=True)),
                ("intake_interested", models.CharField(max_length=255, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("Under Review", "Under Review"),
                            ("Declined", "Declined"),
                            ("Info Requested", "Info Requested"),
                            ("Accepted", "Accepted"),
                        ],
                        default="Under Review",
                        max_length=255,
                    ),
                ),
                (
                    "first_choice_programme",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="first_choice_programme",
                        to="schools.programme",
                    ),
                ),
                (
                    "second_choice_programme",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="second_choice_programme",
                        to="schools.programme",
                    ),
                ),
                (
                    "third_choice_programme",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="third_choice_programme",
                        to="schools.programme",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="ApplicationDocument",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("document_name", models.CharField(max_length=255)),
                ("document_type", models.CharField(max_length=255)),
                ("document_file", models.FileField(upload_to="application_documents/")),
                ("verified", models.BooleanField(default=False)),
                (
                    "student_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admissions.studentapplication",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
