# Generated by Django 5.1.1 on 2024-11-20 09:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admissions", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentapplication",
            name="application_number",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="first_name",
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="last_name",
            field=models.CharField(max_length=255),
        ),
    ]
