# Generated by Django 5.2.5 on 2025-09-29 14:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("admissions", "0002_initial"),
        ("marketing", "0001_initial"),
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentapplication",
            name="lead",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leadapplications",
                to="marketing.lead",
            ),
        ),
        migrations.AddField(
            model_name="studentapplication",
            name="second_choice_programme",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="second_choice_programme",
                to="schools.programme",
            ),
        ),
        migrations.AddField(
            model_name="applicationeducationhistory",
            name="student_application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="admissions.studentapplication",
            ),
        ),
        migrations.AddField(
            model_name="applicationdocument",
            name="student_application",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                to="admissions.studentapplication",
            ),
        ),
    ]
