# Generated by Django 5.1.1 on 2024-11-20 09:56

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admissions", "0003_studentapplication_date_of_birth"),
    ]

    operations = [
        migrations.CreateModel(
            name="ApplicationEducationHistory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("institution", models.CharField(max_length=255)),
                (
                    "level",
                    models.CharField(
                        choices=[
                            ("Primary School", "Primary School"),
                            ("Secondary School", "Secondary School"),
                            ("College", "College"),
                            ("University", "University"),
                        ],
                        max_length=255,
                    ),
                ),
                ("grade", models.CharField(max_length=255, null=True)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField(null=True)),
                ("graduated", models.BooleanField(default=False)),
                (
                    "student_application",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="admissions.studentapplication",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
