# Generated by Django 5.1.1 on 2024-11-20 10:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admissions", "0004_applicationeducationhistory"),
    ]

    operations = [
        migrations.RenameField(
            model_name="applicationeducationhistory",
            old_name="grade",
            new_name="grade_or_gpa",
        ),
        migrations.RemoveField(
            model_name="applicationeducationhistory",
            name="end_date",
        ),
        migrations.RemoveField(
            model_name="applicationeducationhistory",
            name="start_date",
        ),
        migrations.AddField(
            model_name="applicationeducationhistory",
            name="certificate",
            field=models.FileField(null=True, upload_to="application_certificates/"),
        ),
        migrations.AddField(
            model_name="applicationeducationhistory",
            name="major",
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="applicationeducationhistory",
            name="year",
            field=models.CharField(max_length=255, null=True),
        ),
    ]
