# Generated by Django 5.1.1 on 2024-11-20 10:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "admissions",
            "0005_rename_grade_applicationeducationhistory_grade_or_gpa_and_more",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="Intake",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("start_date", models.DateField()),
                ("end_date", models.DateField()),
                ("closed", models.BooleanField(default=False)),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.RemoveField(
            model_name="studentapplication",
            name="intake_interested",
        ),
        migrations.RemoveField(
            model_name="studentapplication",
            name="third_choice_programme",
        ),
    ]
