# Generated by Django 5.1.1 on 2024-11-20 10:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "admissions",
            "0006_intake_remove_studentapplication_intake_interested_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="studentapplication",
            name="intake",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="admissions.intake",
            ),
        ),
    ]
