# Generated by Django 5.1.1 on 2024-11-20 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admissions", "0007_studentapplication_intake"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentapplication",
            name="passport_photo",
            field=models.ImageField(
                blank=True, null=True, upload_to="passport_photos/"
            ),
        ),
    ]
