# Generated by Django 5.1.1 on 2024-11-20 10:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admissions", "0008_studentapplication_passport_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationdocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("Transcript", "Transcript"),
                    ("Certificate", "Certificate"),
                    ("Indentification", "Indentification"),
                ],
                max_length=255,
            ),
        ),
    ]
