# Generated by Django 5.1.1 on 2024-11-20 14:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admissions", "0009_alter_applicationdocument_document_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="applicationeducationhistory",
            name="certificate",
        ),
        migrations.AlterField(
            model_name="applicationeducationhistory",
            name="level",
            field=models.CharField(
                choices=[
                    ("Primary School", "Primary School"),
                    ("Secondary School", "Secondary School"),
                    ("Undergraduate", "Undergraduate"),
                    ("Graduate", "Graduate"),
                ],
                max_length=255,
            ),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("Under Review", "Under Review"),
                    ("Declined", "Declined"),
                    ("Info Requested", "Info Requested"),
                    ("Accepted", "Accepted"),
                    ("Draft", "Draft"),
                ],
                default="Under Review",
                max_length=255,
            ),
        ),
    ]
