# Generated by Django 5.1.1 on 2024-11-20 15:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admissions", "0010_remove_applicationeducationhistory_certificate_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentapplication",
            name="slug",
            field=models.SlugField(null=True, unique=True),
        ),
    ]
