# Generated by Django 5.1.1 on 2024-11-20 15:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admissions", "0011_studentapplication_slug"),
        ("marketing", "0015_leadstage_added_by"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentapplication",
            name="lead",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="leadapplications",
                to="marketing.lead",
            ),
        ),
    ]
