# Generated by Django 5.1.1 on 2024-11-21 09:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admissions", "0012_studentapplication_lead"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationdocument",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("Transcript", "Transcript"),
                    ("Certificate", "Certificate"),
                    ("Identification", "Identification"),
                ],
                max_length=255,
            ),
        ),
    ]
