# Generated by Django 5.1.1 on 2024-11-21 10:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admissions", "0013_alter_applicationdocument_document_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("Under Review", "Under Review"),
                    ("Declined", "Declined"),
                    ("Info Requested", "Info Requested"),
                    ("Accepted", "Accepted"),
                    ("Draft", "Draft"),
                    ("Enrolled", "Enrolled"),
                ],
                default="Under Review",
                max_length=255,
            ),
        ),
    ]
