# Generated by Django 5.1.1 on 2024-11-25 11:32

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("admissions", "0014_alter_studentapplication_status"),
        ("core", "0004_checkin"),
    ]

    operations = [
        migrations.AddField(
            model_name="studentapplication",
            name="campus",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="core.campus",
            ),
        ),
    ]
