# Generated by Django 4.2 on 2025-05-15 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0015_studentapplication_campus"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentapplication",
            name="address",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="city",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="country",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="guardian_email",
            field=models.EmailField(blank=True, max_length=254, null=True),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="guardian_name",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="guardian_phone_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="guardian_relationship",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="id_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="passport_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="postal_code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name="studentapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("Under Review", "Under Review"),
                    ("Declined", "Declined"),
                    ("Info Requested", "Info Requested"),
                    ("Accepted", "Accepted"),
                    ("Draft", "Draft"),
                    ("Enrolled", "Enrolled"),
                    ("Incomplete", "Incomplete"),
                ],
                default="Under Review",
                max_length=255,
            ),
        ),
    ]
