# Generated by Django 4.2 on 2025-05-16 14:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0016_alter_studentapplication_address_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentapplication",
            name="application_number",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
