# Generated by Django 4.2 on 2025-05-16 15:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0017_alter_studentapplication_application_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="studentapplication",
            name="status",
            field=models.CharField(
                choices=[
                    ("Under Review", "Under Review"),
                    ("Declined", "Declined"),
                    ("Info Requested", "Info Requested"),
                    ("Accepted", "Accepted"),
                    ("Draft", "Draft"),
                    ("Enrolled", "Enrolled"),
                    ("Incomplete", "Incomplete"),
                ],
                default="Incomplete",
                max_length=255,
            ),
        ),
    ]
