# Generated by Django 4.2 on 2025-05-16 20:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0018_alter_studentapplication_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="applicationeducationhistory",
            name="major",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
