from django.urls import path
from .views import (
    AcademicYearDetailView,
    AcademicYearsListView,
    CampusCreateView,
    CampusListView,
    CampusUpdateDeleteView,
    CreateAcademicYearView,
    CreateRoleView,
    DashboardCountsRetrieveView,
    LoggedInPermissionsView,
    RecentActionsView,
    RoleDetailPermissionsView,
    RolesListAPIView,
    StudyYearCreateView,
    StudyYearListView,
    StudyYearUpdateDeleteView,
    UpdateDeleteRoleView,
    UpdateRolePermissionsView,
    # UserRoleListView,
)

urlpatterns = [
    path("roles/", RolesListAPIView.as_view(), name="role-list"),
    path("roles/create/", CreateRoleView.as_view(), name="role-create"),
    path("roles/<int:pk>/", UpdateDeleteRoleView.as_view(), name="role-update-delete"),
    path(
        "roles/<int:pk>/permissions/",
        RoleDetailPermissionsView.as_view(),
        name="role-permissions",
    ),
    path(
        "roles/<int:pk>/permissions/update/",
        UpdateRolePermissionsView.as_view(),
        name="role-permissions-update",
    ),
     path("permissions/", LoggedInPermissionsView.as_view(), name="user-permissions"),
    path("campus/create/", CampusCreateView.as_view(), name="campus-create"),
    path("campus/list/", CampusListView.as_view(), name="campus-list"),
    # path("user-roles/", UserRoleListView.as_view(), name="user-role-list"),
    path(
        "campus/update-delete/<int:pk>/",
        CampusUpdateDeleteView.as_view(),
        name="campus-update-delete",
    ),
    path("studyyear/create/", StudyYearCreateView.as_view(), name="studyyear-create"),
    path("studyyear/list/", StudyYearListView.as_view(), name="studyyear-list"),
    path(
        "studyyear/update-delete/<int:pk>/",
        StudyYearUpdateDeleteView.as_view(),
        name="studyyear-update-delete",
    ),
    path("academic-years/create/", CreateAcademicYearView.as_view(), name="academic-year-create"),
    path("academic-years/list/", AcademicYearsListView.as_view(), name="academic-years-list"),
    path(
        "academic-years/<int:pk>/",
        AcademicYearDetailView.as_view(),
        name="academic-years-update-delete",
    ),
    # path("studyyear/list/", StudyYearListView.as_view(), name="studyyear-list"),
    path(
        "dashboard-counts/",
        DashboardCountsRetrieveView.as_view(),
        name="dashboard-counts-metric",
    ),
    path("recent-actions/", RecentActionsView.as_view(), name="recent-actions"),
]
