# Generated by Django 5.1.1 on 2024-11-04 10:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="programme",
            name="code",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
