# Generated by Django 5.1.1 on 2024-11-04 11:17

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0002_programme_code"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="office",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
