# Generated by Django 5.2.5 on 2025-10-05 09:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("core", "0005_alter_academicyear_end_date_and_more"),
        ("schools", "0002_alter_semester_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programmecohort",
            name="current_semester",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="semesters_cohorts",
                to="schools.semester",
            ),
        ),
        migrations.AlterField(
            model_name="programmecohort",
            name="current_year",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cohorts",
                to="core.studyyear",
            ),
        ),
    ]
