# Generated by Django 5.1.1 on 2024-11-07 13:46

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0003_department_office"),
    ]

    operations = [
        migrations.CreateModel(
            name="Semester",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("academic_year", models.CharField(max_length=255)),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
