# Generated by Django 5.2.5 on 2025-10-05 15:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0003_alter_programmecohort_current_semester_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="course",
            name="semester",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="courses",
                to="schools.semester",
            ),
        ),
    ]
