# Generated by Django 5.1.1 on 2024-11-07 14:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0004_semester"),
    ]

    operations = [
        migrations.AlterField(
            model_name="semester",
            name="name",
            field=models.CharField(
                choices=[
                    ("Semester One", "Semester One"),
                    ("Semester Two", "Semester Two"),
                    ("Semester Three", "Semester Three"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
