# Generated by Django 5.1.1 on 2024-11-18 15:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0006_semester_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="semester",
            name="end_date",
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name="semester",
            name="start_date",
            field=models.DateField(null=True),
        ),
    ]
