# Generated by Django 5.1.1 on 2024-11-18 18:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0007_semester_end_date_semester_start_date"),
    ]

    operations = [
        migrations.CreateModel(
            name="ProgrammeCohort",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                (
                    "current_year",
                    models.CharField(
                        choices=[
                            ("First Year", "First Year"),
                            ("Second Year", "Second Year"),
                            ("Third Year", "Third Year"),
                            ("Fourth Year", "Fourth Year"),
                            ("Fifth Year", "Fifth Year"),
                            ("Sixth Year", "Sixth Year"),
                            ("Seventh Year", "Seventh Year"),
                        ],
                        max_length=255,
                    ),
                ),
                (
                    "current_semester",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schools.semester",
                    ),
                ),
                (
                    "programme",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schools.programme",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="CourseSession",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("start_time", models.DateTimeField(null=True)),
                ("period", models.FloatField(default=2)),
                (
                    "course",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="schools.course"
                    ),
                ),
                (
                    "cohort",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="schools.programmecohort",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
    ]
