# Generated by Django 5.1.1 on 2024-11-18 20:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0009_coursesession_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="programmecohort",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Closed", "Closed")],
                max_length=255,
                null=True,
            ),
        ),
    ]
