# Generated by Django 5.1.1 on 2024-11-18 20:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0011_alter_coursesession_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programmecohort",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Closed", "Closed")],
                default="Active",
                max_length=255,
            ),
        ),
    ]
