# Generated by Django 5.1.1 on 2024-11-19 08:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0012_alter_programmecohort_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="programmecohort",
            name="status",
            field=models.CharField(
                choices=[("Active", "Active"), ("Graduated", "Graduated")],
                default="Active",
                max_length=255,
            ),
        ),
    ]
