# Generated by Django 5.1.1 on 2024-11-19 08:43

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0013_alter_programmecohort_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursesession",
            name="status",
            field=models.CharField(
                choices=[
                    ("Active", "Active"),
                    ("Completed", "Completed"),
                    ("Cancelled", "Cancelled"),
                    ("Rescheduled", "Rescheduled"),
                ],
                default="Active",
                max_length=255,
            ),
        ),
    ]
