# Generated by Django 5.1.1 on 2024-11-19 12:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("schools", "0015_alter_coursesession_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="coursesession",
            name="cohort",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="cohortsessions",
                to="schools.programmecohort",
            ),
        ),
    ]
