# Generated by Django 4.2 on 2025-06-03 15:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0016_alter_coursesession_cohort"),
    ]

    operations = [
        migrations.AddField(
            model_name="department",
            name="department_type",
            field=models.CharField(
                choices=[("Academic", "Academic"), ("Not Academic", "Not Academic")],
                default="Academic",
                max_length=15,
            ),
        ),
        migrations.AlterField(
            model_name="department",
            name="school",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="schools.school",
            ),
        ),
    ]
