# Generated by Django 4.2 on 2025-06-19 07:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("admissions", "0019_alter_applicationeducationhistory_major"),
        ("schools", "0017_department_department_type_alter_department_school"),
    ]

    operations = [
        migrations.AddField(
            model_name="programmecohort",
            name="intake",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="admissions.intake",
            ),
        ),
    ]
