# Generated by Django 5.2.5 on 2025-08-19 18:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0018_programmecohort_intake"),
    ]

    operations = [
        migrations.AddField(
            model_name="coursesession",
            name="semester",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="semesterssessions",
                to="schools.semester",
            ),
        ),
    ]
