# Generated by Django 5.2.5 on 2025-08-19 19:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0019_coursesession_semester"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="study_year",
            field=models.CharField(
                blank=True,
                choices=[
                    ("First Year", "First Year"),
                    ("Second Year", "Second Year"),
                    ("Third Year", "Third Year"),
                    ("Fourth Year", "Fourth Year"),
                    ("Fifth Year", "Fifth Year"),
                    ("Sixth Year", "Sixth Year"),
                    ("Seventh Year", "Seventh Year"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
