# Generated by Django 5.2.5 on 2025-08-19 19:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0020_course_study_year"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="credit_hours",
            field=models.FloatField(default=2.0),
        ),
    ]
