# Generated by Django 5.2.5 on 2025-08-19 19:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0022_course_semester"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="course",
            name="semester",
        ),
    ]
