# Generated by Django 5.2.5 on 2025-08-19 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0023_remove_course_semester"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="semester",
            field=models.CharField(
                blank=True,
                choices=[
                    ("Semester One", "Semester One"),
                    ("Semester Two", "Semester Two"),
                    ("Semester Three", "Semester Three"),
                ],
                max_length=255,
                null=True,
            ),
        ),
    ]
