# Generated by Django 5.2.5 on 2025-08-19 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("schools", "0024_course_semester"),
    ]

    operations = [
        migrations.AddField(
            model_name="course",
            name="course_type",
            field=models.CharField(
                choices=[
                    ("Core", "Core"),
                    ("Elective", "Elective"),
                    ("Optional", "Optional"),
                ],
                default="Core",
                max_length=255,
            ),
        ),
    ]
