# Generated by Django 5.1.1 on 2024-11-15 12:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("core", "0002_campus"),
        ("hostels", "0002_booking_status"),
        ("students", "0008_student_programme"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="booking",
            name="address",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="amount",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="city",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="country",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="email",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="first_name",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="gender",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="guardian_name",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="guardian_phone_number",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="last_name",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="mpesa_code",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="phone_number",
        ),
        migrations.RemoveField(
            model_name="booking",
            name="registration_number",
        ),
        migrations.AddField(
            model_name="booking",
            name="student",
            field=models.OneToOneField(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="students.student",
            ),
        ),
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending Check-In", "Pending Check-In"),
                    ("Checked In", "Checked In"),
                    ("Checked Out", "Checked Out"),
                ],
                default="Pending",
                max_length=255,
            ),
        ),
        migrations.CreateModel(
            name="Hostel",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("name", models.CharField(max_length=255)),
                ("rooms", models.IntegerField(default=1)),
                (
                    "room_cost",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("capacity", models.IntegerField(default=1)),
                (
                    "gender",
                    models.CharField(
                        choices=[("Male", "Male"), ("Female", "Female")],
                        max_length=255,
                        null=True,
                    ),
                ),
                (
                    "campus",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="core.campus",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.CreateModel(
            name="HostelRoom",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_on", models.DateTimeField(auto_now_add=True)),
                ("updated_on", models.DateTimeField(auto_now=True)),
                ("room_number", models.CharField(max_length=255)),
                ("room_capacity", models.IntegerField(default=1)),
                ("students_assigned", models.IntegerField(default=0)),
                ("fully_booked", models.BooleanField(default=False)),
                (
                    "hostel",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="hostels.hostel",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
        ),
        migrations.AddField(
            model_name="booking",
            name="hostel_room",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="hostels.hostelroom",
            ),
        ),
    ]
