# Generated by Django 5.1.1 on 2024-11-17 09:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("hostels", "0003_remove_booking_address_remove_booking_amount_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="hostel",
            name="gender",
            field=models.CharField(
                choices=[("Male", "Male"), ("Female", "Female"), ("Mixed", "Mixed")],
                max_length=255,
                null=True,
            ),
        ),
    ]
