# Generated by Django 5.1.1 on 2024-11-21 12:18

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("hostels", "0004_alter_hostel_gender"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="hostelroom",
            name="fully_booked",
        ),
    ]
