# Generated by Django 4.2 on 2025-05-29 10:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostels", "0005_remove_hostelroom_fully_booked"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending Check-In", "Pending Check-In"),
                    ("Checked In", "Checked In"),
                    ("Checked Out", "Checked Out"),
                ],
                default="Pending Check-In",
                max_length=255,
            ),
        ),
    ]
