# Generated by Django 4.2 on 2025-05-30 11:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("hostels", "0006_alter_booking_status"),
    ]

    operations = [
        migrations.AlterField(
            model_name="booking",
            name="status",
            field=models.CharField(
                choices=[
                    ("Pending", "Pending"),
                    ("Confirmed", "Confirmed"),
                    ("Cancelled", "Cancelled"),
                ],
                default="Pending",
                max_length=255,
            ),
        ),
    ]
