# Generated by Django 4.2 on 2025-08-09 09:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("accounting", "0007_remove_accounttype_cash_flow_section_and_more"),
        ("payroll", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="salarypayment",
            name="journal_entry",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="salary_payments",
                to="accounting.journalentry",
            ),
        ),
    ]
