# Generated by Django 4.2 on 2025-08-09 10:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0002_salarypayment_journal_entry"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salarypayment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("Cash", "Cash"),
                    ("Bank Transfer", "Bank Transfer"),
                    ("Mobile Money", "Mobile Money"),
                    ("Cheque", "Cheque"),
                ],
                default="bank",
                max_length=50,
            ),
        ),
    ]
