# Generated by Django 4.2 on 2025-08-09 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("payroll", "0003_alter_salarypayment_payment_method"),
    ]

    operations = [
        migrations.AlterField(
            model_name="salarypayment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("Cash", "Cash"),
                    ("Bank", "Bank Transfer"),
                    ("Mpesa", "Mpesa"),
                    ("Cheque", "Cheque"),
                ],
                default="bank",
                max_length=50,
            ),
        ),
    ]
